steps:
- name: 'gcr.io/kaniko-project/executor'
  id: build
  args: [
    '--snapshotMode=redo',
    '--use-new-run=true',
    '--dockerfile=build.Dockerfile',
    '--context=.',
    '--destination=gcr.io/$PROJECT_ID/$_APP:$BUILD_ID',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  waitFor: ['build']
  args: [
    'gcloud', 'beta', 'run', 'deploy',
    '$_APP-ext-$_DEPLOY_REGION_PRIMARY',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP:$BUILD_ID',
    '--region', '$_DEPLOY_REGION_PRIMARY',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  waitFor: ['build']
  args: [
    'gcloud', 'beta', 'run', 'deploy',
    '$_APP-ext-$_DEPLOY_REGION_FALLBACK',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP:$BUILD_ID',
    '--region', '$_DEPLOY_REGION_FALLBACK',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  waitFor: ['build']
  args: [
    'gcloud', 'beta', 'run', 'deploy',
    '$_APP-int-$_DEPLOY_REGION_PRIMARY',
    '--platform', 'managed',
    '--image', 'gcr.io/$PROJECT_ID/$_APP:$BUILD_ID',
    '--region', '$_DEPLOY_REGION_PRIMARY',
    '--update-env-vars', 'BUILD_REPO=$REPO_NAME,BUILD_REV=$COMMIT_SHA',
  ]
substitutions:
    _APP: hubauth
    _DEPLOY_REGION_PRIMARY: us-central1
    _DEPLOY_REGION_FALLBACK: us-west1
